### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by Tazintosh** [cloudfs/ftp-cloudfs#35]
Hi folks,

I definitely need your help.
I know it's a little aside ftpcloudfs by itself but I hope you will be able to provide me some ideas:

So, I'm trying to run ftpcloudfs on Mac OS X Yosemite (+ Server.app installed).
Installation went perfectly, I've done the following config:

	[ftpcloudfs]
	split-large-files = 512
	hide-part-dir = yes
	auth-url = https://myServerDomain:8890/auth/v1.0/
	bind-address = 192.168.1.11
	masquerade-firewall = myPublicIP
	insecure = yes

:8890 is when I test with MAMP, else, it's https://myServerDomain/auth/v1.0/ with default OS X Apache.
With MAMP, I'm using a MAMP create autosigned certificate+key
With Apple's Apache, I'm using an Apple autosigned certificate+key create right into the Server.app
I'm using hubic2swiftgate for authentification and it's working. (ie. https://myServerDomain/usage/ does display my quotas, so identification to hubiC is working).
Anyway, the result is the same I can not login with my FTP client (set to ftp://hubic@192.168.1.11:2021) :(

Error With Apple Apache

	[E 14-11-25 19:59:14] 192.168.1.11:64096-[hubic] Failed to authenticate user hubic: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol
	[13683] 2014-11-25 19:59:14,996 - ERROR - 192.168.1.11:64096-[hubic] Failed to authenticate user hubic: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol

Error with MAMP

	[54610] 2014-11-28 18:53:34,687 - INFO - Starting new HTTPS connection (1): myServerDomain
	/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/	en/latest/security.html (This warning will only appear once by default.)
  	InsecureRequestWarning)
	[54610] 2014-11-28 18:53:34,699 - INFO - REQ: curl -i https://myServerDomain:8890/auth/v1.0/ -X GET
	[54610] 2014-11-28 18:53:34,700 - INFO - RESP STATUS: 403 Forbidden
	[54610] 2014-11-28 18:53:34,700 - INFO - RESP HEADERS: [('content-length', '212'), ('keep-alive', 'timeout=5, max=100'), ('server', 'Apache'), ('connection', 'Keep-Alive'), ('date', 'Fri, 28 Nov 2014 17:53:34 GMT'), ('content-	type', 'text/html; charset=iso-8859-1')]
	[54610] 2014-11-28 18:53:34,700 - INFO - RESP BODY: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
	<html><head>
	<title>403 Forbidden</title>
	</head><body>
	<h1>Forbidden</h1>
	<p>You don't have permission to access /auth/v1.0/
	on this server.</p>
	</body></html>
	[E 14-11-28 18:53:34] 192.168.1.11:59039-[hubic] Failed to authenticate user hubic: [Errno 13] Auth GET failed: 	Forbidden
	[54610] 2014-11-28 18:53:34,700 - ERROR - 192.168.1.11:59039-[hubic] Failed to authenticate user hubic: [Errno 13] Auth 	GET failed: Forbidden
	[I 14-11-28 18:53:39] 192.168.1.11:59039-[] USER 'hubic' failed login.
	[54610] 2014-11-28 18:53:39,702 - INFO - 192.168.1.11:59039-[] USER 'hubic' failed login.
	[I 14-11-28 18:53:42] 192.168.1.11:59039-[] FTP session closed (disconnect).
	[54610] 2014-11-28 18:53:42,962 - INFO - 192.168.1.11:59039-[] FTP session closed (disconnect).

Thanks for any help!

**Comment by Tazintosh** [comment]
Hi Juan. I made it work!

For this, I had to edit `/Library/Python/2.7/site-packages/requests-2.5.0-py2.7.egg/requests/adapters.py` 

Around line 12, I've added `import ssl`  
Around line 133, I've added `ssl_version=ssl.PROTOCOL_TLSv1` like so:

	self.poolmanager = PoolManager(num_pools=connections, maxsize=maxsize, block=block, strict=True, ssl_version=ssl.PROTOCOL_TLSv1, **pool_kwargs)

Actually, it's only working with Apple's Apache https server. MAMP Pro is not working, which for me is not a big deal at this point, it's even better with default Apple's server. Still, it's probably just some default settings to change.
I'm actually deleting files stored on hubiC from two different computers, it's running without a glitch for the moment:
• My Mac mini is running the https gateway + ftpcloudfs and is deleting files with my Forklift FTP client
• My Mac Pro is deleting some other files with my Forklift FTP client connected to ftpcloudfs running on the Mac mini.

Thanks for your time and help.
Cheers

**Comment by reidrac** [comment]
Makes sense, that was explained in a thread. The problem seems related with the openssl version shipped with Yosemite. My suggestion was to remove any SSL protocols but TLS, but patching requests to explicitly use TLSv1 is a good solution too!

I'm glad it works for you :)
