### ISSUE TITLE
Feature request: append-mode file descriptors

### ISSUE THREAD

**Issue by kvdveer** [cloudfs/ftp-cloudfs#4]
For FTP resume support, pyftpdlib needs to open files in append mode. 

To implement this, I'd create a file descriptor which downloads the specified object to local storage, possibly in the background. On closing or syncing the FD, it would get copied back to the backend. As a side effect, this solution would allow read-write file descriptors and seeking.

This solution isn't perfect, however:
- There are some obvious performance problems (slow open/close/sync)
- There is a race condition while the FD is open and not synced.
- This potentially requires quite a bit of local storage.

However, for our usecase none of these are unacceptable problems. I'd implement this, but before doing so, I'd love some feedback.

**Comment by reidrac** [comment]
Feel free to reopen this with a patch!
