### ISSUE TITLE
split-large-file collisions with existing `.part` files

### ISSUE THREAD

**Issue by reidrac** [cloudfs/ftp-cloudfs#56]
This was described in #54.

Copied from there:

After upload object with bigger size than `split-large-files` setting, we got DLO-manifest + segments in path like 'OBJECT_NAME.part/XXXXXX'. FTP-protocol allow us to rename objects and it works fine with object less in size than `split-large-files`. But renaming DLO-manifest isn't rename its segments (and that 'OBJECT_NAME.part' "directory" hidden from ftp-listing if `hide-part-dir = yes`.

So in some workflows we got interesting results. For example:
- upload object '1.file' larger than `split-large-file`;
- rename '1.file' to '1.file.bak';
- upload '1.file' with new content (larger than `split-large-file` of course);
- now both '1.file' and '1.file.bak' point to same '.part' "directory" in 'X-Object-Manifest' header (and data of object corrupted as well).

When a `.part` directory is created, we should check if it already exists and use an alternative name.

**Comment by vills** [comment]
Morning! Any updates on issue?

**Comment by reidrac** [comment]
I've been thinking on this one and I've found a way to fix it (not trivial though).

We can't rename the "parts" when the manifest is renamed, so I have to detect collisions (to use an different "parts" file), and still support overwriting files.

**Comment by reidrac** [comment]
I've pushed a branch that solves the problem:

https://github.com/cloudfs/ftp-cloudfs/tree/split-large-file-collisions

There are still cases where we will get stale parts after a rename/overwrite; but that can't be fixed and is a limitation we accepted when renames of large split-files was implemented.

Please give it a go!

**Comment by vills** [comment]
Hi,

Looks like it works, but with some fun :-). On each chunk of data in FD function _find_collisions is called. So web got LOOOOTs of HEAD requests to storage while uploading.

**Comment by reidrac** [comment]
There will be HEAD requests. They're cheap... and I'm not sure if there's any other way of detecting the collisions.

But you're right, I'm overchecking :) -- let me update the branch to check for collisions only when it is a multi-part file.

**Comment by vills** [comment]
There is no way to check for collisions once while FD create?

**Comment by reidrac** [comment]
My idea was to check for the collision when the write of a multi-part file starts, but I made a mistake and it was checking for every file. Let me fix it and I think it'd be fine!

**Comment by reidrac** [comment]
I've updated the branch:

https://github.com/cloudfs/ftp-cloudfs/tree/split-large-file-collisions

Can you give it another go? I think this time is right :) Thanks!

**Comment by vills** [comment]
Replied in commit. This time isn't right, sorry :-)

**Comment by reidrac** [comment]
Yes, I see. Thanks for your review.

**Comment by reidrac** [comment]
Updated the branch, this time to check for collisions when the FD is created.

If it isn't a multi-part file, it will make an extra HEAD request that isn't really used for anything.

Thanks again for your tests.

**Comment by vills** [comment]
Check pull #58 plz

**Comment by reidrac** [comment]
I see you're describing in #58 another issue when an object is overwritten without changing the name.

I rather deal with that in a different change (we could remove the old parts that haven't been overwritten; that should be straightforward).

Did the last change fix the issue of collisions after a rename?

**Comment by vills** [comment]
Maybe its another issue in #58, but changes also cover that one. In case of DLO you can't be sure, you deleted all remaining old part, cause of eventually consistency of swift. We make same logic for any overwrite case.

Yes, last change helps. But store any overwrites to other path is better, I think.

**Comment by reidrac** [comment]
The overwrite problem can be solved in a different way; we can avoid collision and delete the old objects in bg or similar.

Otherwise you're going to left a lot of stale objects once you overwrite.

I rather fix one thing at a time. If you're happy with this one, I can merge the change and then look at the overwrite problem in a different bug report.

**Comment by vills** [comment]
Ok. i understood you. Yep, this issue is resolved.

**Comment by reidrac** [comment]
Thanks! 

Filed #59 to deal with the collisions when overwriting files.

**Comment by vills** [comment]
Thanks
