### ISSUE TITLE
Option to overwrite storage_url got from auth service

### ISSUE THREAD

**Issue by vills** [cloudfs/ftp-cloudfs#60]
It is enhancement proposal.

What is about an option in config to tell FTP use another swift URL, not one got from response to auth?

Let's say you have 10 servers running swift-proxy and ftp-cloudfs instances. Storage URL in auth point to myswift.com, which have 10 A-reconds in DNS to 10 servers with swift-proxy. Everything works ok in that case. But you can experience unwanted network traffic and larger response times, while work with FTP, cause FTP from server1 get connected to swift-proxy on server2 (either it's local network, lo interface still much faster).

Better decision in that case would be: each ftp-cloudfs instance use local swift-proxy instance (or local load balancer instance, that will point to server2 in case local swift-proxy is dead).

Ftp-cloudfs should be able to overwrite:
- `endpoint.scheme`: HTTP or HTTPS;
- `endpoint.ssl_verification`: no way to connect to SSL'ed service, if hostnames doesn't match (or not check SSL in case of overwritten endpoint);
- `endpoint.hostname`
- `endpoint.port`

If you see any cases where overwrite of other endpoint parts need, you'r welcome :-).

Thanks for spending time on reading it ;-).

**Comment by reidrac** [comment]
We can't accept this as is breaking how the API should behave: you should get the proxy URL from the auth request.

This is a local change or something that only makes sense in your setup, sorry.
