### ISSUE TITLE
Error when I use keystone version 3

### ISSUE THREAD

**Issue by longlnk** [cloudfs/ftp-cloudfs#66]
I use keystone version 3 and it appear error as below:

> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: keystone authurl='http://controller-r2:5000/v3' username=u'admin' tenant_name=u'admin' conf={'service_type': 'object-store', 'endpoint_type': 'publicURL', 'tenant_separator': '.', 'region_name': 'regionOne'}
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: Test authurl='http://controller-r2:5000/v3' username=u'admin' tenant_name=u'admin' key=u'adminpass@345qwe'
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: token cache miss 1, key=tk71f22c27799e7cecb3c98aadfc50c8ea
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: Making authentication request to http://controller-r2:5000/v3/tokens
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: Starting new HTTP connection (1): controller-r2:5000
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: http://controller-r2:5000 "POST /v3/tokens HTTP/1.1" 404 93
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: Request returned failure status: 404
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: At authenticate: Authorization Failure. Authorization Failed: The resource could not be found. (HTTP 404) (Request-ID: req-4d00e755-940e-4e8f-bf54-20590f30a17d):
> Oct 16 05:41:29 webserver-r2 ftpcloudfs[22615]: 203.162.141.87:63402-[admin.admin] Failed to authenticate user admin.admin: [Errno 5] Authorization Failure. Authorization Failed: The resource could not be found. (HTTP 404) (Request-ID: req-4d00e755-940e-4e8f-bf54-20590f30a17d):
> 

Please help me :(

**Comment by reidrac** [comment]
We haven't implemented Keystone v3, it is currently not supported.

**Comment by longlnk** [comment]
> We haven't implemented Keystone v3, it is currently not supported.

Do you have a plan for development?

**Comment by reidrac** [comment]
Fixed by #67
