### ISSUE TITLE
Alternative authentication (aka: swauth is deprecated)

### ISSUE THREAD

**Issue by drzraf** [cloudfs/ftp-cloudfs#76]
https://github.com/openstack/swauth => https://opendev.org/x/swauth

One big advantage of `ftp-cloudfs` is that Swift ACL are not flexible and configuring them is not simple.

Wrapping the protocol is great. Wrapping authentication and permission would be even greater.
=> Eg: Authenticate (and authorize resources) by defining credentials in a simple `ini/yaml/json-file`?

**Comment by reidrac** [comment]
The service supports OpenStack Identity Service (Keystone) v2.0 and v3. Currently there are no plans to support any other auth backend.
